import { Inter } from "next/font/google";
import Link from "next/link";
import '../styles/globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <nav className="flex justify-between bg-gray-900 text-white w-screen">
        <div className="px-5 xl:px-12 py-6 flex w-full items-center">
          <Link className="text-3xl font-bold font-heading" href="/">
            Rechtsrutsch DE
          </Link>

          <ul className="hidden md:flex px-4 mx-auto font-semibold font-heading space-x-12">
            <li><Link className="hover:text-gray-200" href="/">Home</Link></li>
            <li><Link className="hover:text-gray-200" href="/armut-in-deutschland">Armut in DE</Link></li>
            <li><Link className="hover:text-gray-200" href="/">Die AfD</Link></li>
            <li><Link className="hover:text-gray-200" href="/"></Link></li>
          </ul>
        </div>
      </nav>

      <main className={inter.className}>
        {children} {/* Hier wird der Inhalt von den Unterseiten geladen */}
      </main>
    </>
  );
}
